### ISSUE TITLE
SSD Model support

### ISSUE THREAD

**Issue by kumardesappan** [asiryan/caffe-onnx#1]
Hi, 
Addition of SSD models support would be useful. Do you have any plans to add support for the same?
Example of caffe SSD model can be found here
https://github.com/chuanqi305/MobileNet-SSD

Also Argmax layer support is missing, this would be useful to support segmentation models

**Comment by kumardesappan** [comment]
Below can be considered as reference for this request (Permute, Prior Box Layers)
https://github.com/apache/tvm/pull/6000/files

**Comment by asiryan** [comment]
Hey! Thanks for the correct point. Later I will add new layers for SSD support.

**Comment by asiryan** [comment]
> Below can be considered as reference for this request (Permute, Prior Box Layers) https://github.com/apache/tvm/pull/6000/files

Hi. Check the new version of the converter. Added support for new layers. 
https://github.com/FaceONNX/caffe2onnx/releases/tag/v2.0.1

**Comment by devsharma15** [comment]
Hi @asiryan, have you tried adding support for "permute" layer for SSD (caffe) to ONNX conversion? or if you are planning to do it in future. Thank you!!
