### ISSUE TITLE
Error in converting caffe_xilinx model to onnx

### ISSUE THREAD

**Issue by RajiSRL** [asiryan/caffe-onnx#2]
Hi @asiryan 
 I am trying to convert a caffe_xilinx yolov3 model to onnx.I got this error during conversion 

> google.protobuf.text_format.ParseError: 2027:3 : Message type "caffe.LayerParameter" has no field named "deephi_resize_param"

I think this deephi_resize_param would be a custom layer built in caffe-xilinx.Can u add support for custom layers ?

**Comment by asiryan** [comment]
Caffe to ONNX converter does not support custom layers.

**Comment by RajiSRL** [comment]
Hi @asiryan ,
I have converted the custom model to onnx by compiling the custom caffe proto file as mentioned in this https://github.com/htshinichi/caffe-onnx

**Comment by asiryan** [comment]
Hi. Check the new version of the converter. Added support for new layers. 
https://github.com/FaceONNX/caffe2onnx/releases/tag/v2.0.1
