### ISSUE TITLE
Potentially Incorrect Output?

### ISSUE THREAD

**Issue by Mayur28** [asiryan/caffe-onnx#3]
Hi!

Thank you for creating this repo, this was exactly what I was looking for!

I am trying to convert a caffe model to onnx, however, it seems that when I test the model with the same input, the output of the onnx model is different to the original caffe model.

I have attached a link to the .caffemodel and .prototxt that I am working with (as well as the produced onnx model) - github would not allow me to upload a zip file containing the models :( -->   https://1drv.ms/u/s!AsfDc4tZ90mEmHlnImwWfaC1asOM
When passing an input image (the input_name is "data_input") of size (1,3,500,500), the caffe model produces the correct output with size (1,21,500, 500) (this is the shape of `net.blobs['score'].data.shape`), whereas the onnx model produces an output with size (1,3, 500,500). I am using the latest version of caffe2onnx.

Any assistance would be highly appreciated.

Thanks!

**Comment by asiryan** [comment]
Hi, thank you for your feedback.
I tested your model with this script

```python
import cv2
import argparse
import numpy as np
import onnxruntime

# main
parser=argparse.ArgumentParser()
parser.add_argument("-i", "--image", type=str, required=False, help="input image")
args=parser.parse_args()

caffeProto="face_seg_fcn8s_deploy.prototxt"
caffeModel="face_seg_fcn8s.caffemodel"
onnxModel="face_seg_fcn8s_deploy.onnx"

caffeNet=cv2.dnn.readNet(caffeModel, caffeProto)
onnxNet=cv2.dnn.readNetFromONNX(onnxModel)
MODEL_MEAN_VALUES=(0, 0, 0)

frame=cv2.imread(args.image if args.image else 'face.jpg')

# caffe net
blob=cv2.dnn.blobFromImage(frame, 1.0, (500,500), MODEL_MEAN_VALUES, swapRB=False)
caffeNet.setInput(blob)
caffeNetPreds=caffeNet.forward()
print(caffeNetPreds.shape)

# onnx net
session = onnxruntime.InferenceSession(onnxModel)
input_name = session.get_inputs()[0].name

img = np.transpose(frame, [2, 0, 1])
img = np.expand_dims(img, axis=0)
img = img.astype(np.float32)

onnxNetPreds = session.run(None, {input_name: img})[0]
print(onnxNetPreds.shape)
```
and got different shapes of outputs
```python
(1, 21, 500, 500) # caffe net
(1, 3, 500, 500) # onnx net
```
I think that something wrong with prototxt file.

**Comment by asiryan** [comment]
Also I noticed that the model is in caffe_v2 format. It is not compatible with caffe2onnx, converter works ONLY with caffe (version 1) models.

**Comment by Mayur28** [comment]
Hi @asiryan,

Thank you for your feedback.

**Comment by Mayur28** [comment]
Hi @asiryan ,

I am still trying to investigate/research what is the best way to convert my caffe model to ONNX, but I was hoping that I could clarify a few things please.

1) From your experiment, I just wanted to find out what makes you think that there is something wrong with the prototxt file? I am using the pre-trained model from [this ](https://github.com/YuvalNirkin/face_segmentation) repo (specially the one in the `face_seg_fcn8s.zip` file).
2) I have never worked with anything relating to caffe and just wanted to find out how were you able to tell that the model is in caffe_v2 format? The repo from which I am using the model states that Caffe (minimum version 1.0) can be used.

Any assistance would be highly appreciated.

Thanks
